// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	readme "github.com/liveoaklabs/readme-api-go-client/readme"
	mock "github.com/stretchr/testify/mock"
)

// MockApplyService is an autogenerated mock type for the ApplyService type
type MockApplyService struct {
	mock.Mock
}

type MockApplyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplyService) EXPECT() *MockApplyService_Expecter {
	return &MockApplyService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: application
func (_m *MockApplyService) Apply(application readme.Application) (readme.ApplyResponse, *readme.APIResponse, error) {
	ret := _m.Called(application)

	var r0 readme.ApplyResponse
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(readme.Application) (readme.ApplyResponse, *readme.APIResponse, error)); ok {
		return rf(application)
	}
	if rf, ok := ret.Get(0).(func(readme.Application) readme.ApplyResponse); ok {
		r0 = rf(application)
	} else {
		r0 = ret.Get(0).(readme.ApplyResponse)
	}

	if rf, ok := ret.Get(1).(func(readme.Application) *readme.APIResponse); ok {
		r1 = rf(application)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(readme.Application) error); ok {
		r2 = rf(application)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockApplyService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockApplyService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - application readme.Application
func (_e *MockApplyService_Expecter) Apply(application interface{}) *MockApplyService_Apply_Call {
	return &MockApplyService_Apply_Call{Call: _e.mock.On("Apply", application)}
}

func (_c *MockApplyService_Apply_Call) Run(run func(application readme.Application)) *MockApplyService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(readme.Application))
	})
	return _c
}

func (_c *MockApplyService_Apply_Call) Return(_a0 readme.ApplyResponse, _a1 *readme.APIResponse, _a2 error) *MockApplyService_Apply_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockApplyService_Apply_Call) RunAndReturn(run func(readme.Application) (readme.ApplyResponse, *readme.APIResponse, error)) *MockApplyService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields:
func (_m *MockApplyService) Get() ([]readme.OpenRole, *readme.APIResponse, error) {
	ret := _m.Called()

	var r0 []readme.OpenRole
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]readme.OpenRole, *readme.APIResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []readme.OpenRole); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]readme.OpenRole)
		}
	}

	if rf, ok := ret.Get(1).(func() *readme.APIResponse); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockApplyService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockApplyService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockApplyService_Expecter) Get() *MockApplyService_Get_Call {
	return &MockApplyService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockApplyService_Get_Call) Run(run func()) *MockApplyService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplyService_Get_Call) Return(_a0 []readme.OpenRole, _a1 *readme.APIResponse, _a2 error) *MockApplyService_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockApplyService_Get_Call) RunAndReturn(run func() ([]readme.OpenRole, *readme.APIResponse, error)) *MockApplyService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplyService creates a new instance of MockApplyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplyService {
	mock := &MockApplyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
