// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	readme "github.com/liveoaklabs/readme-api-go-client/readme"
	mock "github.com/stretchr/testify/mock"
)

// MockOutboundIPService is an autogenerated mock type for the OutboundIPService type
type MockOutboundIPService struct {
	mock.Mock
}

type MockOutboundIPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboundIPService) EXPECT() *MockOutboundIPService_Expecter {
	return &MockOutboundIPService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *MockOutboundIPService) Get() ([]readme.OutboundIP, *readme.APIResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []readme.OutboundIP
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]readme.OutboundIP, *readme.APIResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []readme.OutboundIP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]readme.OutboundIP)
		}
	}

	if rf, ok := ret.Get(1).(func() *readme.APIResponse); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOutboundIPService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOutboundIPService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockOutboundIPService_Expecter) Get() *MockOutboundIPService_Get_Call {
	return &MockOutboundIPService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockOutboundIPService_Get_Call) Run(run func()) *MockOutboundIPService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOutboundIPService_Get_Call) Return(_a0 []readme.OutboundIP, _a1 *readme.APIResponse, _a2 error) *MockOutboundIPService_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOutboundIPService_Get_Call) RunAndReturn(run func() ([]readme.OutboundIP, *readme.APIResponse, error)) *MockOutboundIPService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboundIPService creates a new instance of MockOutboundIPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboundIPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboundIPService {
	mock := &MockOutboundIPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
