// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	readme "github.com/liveoaklabs/readme-api-go-client/readme"
	mock "github.com/stretchr/testify/mock"
)

// MockChangelogService is an autogenerated mock type for the ChangelogService type
type MockChangelogService struct {
	mock.Mock
}

type MockChangelogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangelogService) EXPECT() *MockChangelogService_Expecter {
	return &MockChangelogService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: params
func (_m *MockChangelogService) Create(params readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error) {
	ret := _m.Called(params)

	var r0 readme.Changelog
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(readme.ChangelogParams) readme.Changelog); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(readme.Changelog)
	}

	if rf, ok := ret.Get(1).(func(readme.ChangelogParams) *readme.APIResponse); ok {
		r1 = rf(params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(readme.ChangelogParams) error); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChangelogService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChangelogService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - params readme.ChangelogParams
func (_e *MockChangelogService_Expecter) Create(params interface{}) *MockChangelogService_Create_Call {
	return &MockChangelogService_Create_Call{Call: _e.mock.On("Create", params)}
}

func (_c *MockChangelogService_Create_Call) Run(run func(params readme.ChangelogParams)) *MockChangelogService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(readme.ChangelogParams))
	})
	return _c
}

func (_c *MockChangelogService_Create_Call) Return(_a0 readme.Changelog, _a1 *readme.APIResponse, _a2 error) *MockChangelogService_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChangelogService_Create_Call) RunAndReturn(run func(readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error)) *MockChangelogService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: slug
func (_m *MockChangelogService) Delete(slug string) (bool, *readme.APIResponse, error) {
	ret := _m.Called(slug)

	var r0 bool
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, *readme.APIResponse, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) *readme.APIResponse); ok {
		r1 = rf(slug)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(slug)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChangelogService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChangelogService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - slug string
func (_e *MockChangelogService_Expecter) Delete(slug interface{}) *MockChangelogService_Delete_Call {
	return &MockChangelogService_Delete_Call{Call: _e.mock.On("Delete", slug)}
}

func (_c *MockChangelogService_Delete_Call) Run(run func(slug string)) *MockChangelogService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChangelogService_Delete_Call) Return(_a0 bool, _a1 *readme.APIResponse, _a2 error) *MockChangelogService_Delete_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChangelogService_Delete_Call) RunAndReturn(run func(string) (bool, *readme.APIResponse, error)) *MockChangelogService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: slug
func (_m *MockChangelogService) Get(slug string) (readme.Changelog, *readme.APIResponse, error) {
	ret := _m.Called(slug)

	var r0 readme.Changelog
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (readme.Changelog, *readme.APIResponse, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) readme.Changelog); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(readme.Changelog)
	}

	if rf, ok := ret.Get(1).(func(string) *readme.APIResponse); ok {
		r1 = rf(slug)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(slug)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChangelogService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockChangelogService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - slug string
func (_e *MockChangelogService_Expecter) Get(slug interface{}) *MockChangelogService_Get_Call {
	return &MockChangelogService_Get_Call{Call: _e.mock.On("Get", slug)}
}

func (_c *MockChangelogService_Get_Call) Run(run func(slug string)) *MockChangelogService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChangelogService_Get_Call) Return(_a0 readme.Changelog, _a1 *readme.APIResponse, _a2 error) *MockChangelogService_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChangelogService_Get_Call) RunAndReturn(run func(string) (readme.Changelog, *readme.APIResponse, error)) *MockChangelogService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: options
func (_m *MockChangelogService) GetAll(options ...readme.RequestOptions) ([]readme.Changelog, *readme.APIResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []readme.Changelog
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(...readme.RequestOptions) ([]readme.Changelog, *readme.APIResponse, error)); ok {
		return rf(options...)
	}
	if rf, ok := ret.Get(0).(func(...readme.RequestOptions) []readme.Changelog); ok {
		r0 = rf(options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]readme.Changelog)
		}
	}

	if rf, ok := ret.Get(1).(func(...readme.RequestOptions) *readme.APIResponse); ok {
		r1 = rf(options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(...readme.RequestOptions) error); ok {
		r2 = rf(options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChangelogService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockChangelogService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - options ...readme.RequestOptions
func (_e *MockChangelogService_Expecter) GetAll(options ...interface{}) *MockChangelogService_GetAll_Call {
	return &MockChangelogService_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]interface{}{}, options...)...)}
}

func (_c *MockChangelogService_GetAll_Call) Run(run func(options ...readme.RequestOptions)) *MockChangelogService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]readme.RequestOptions, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(readme.RequestOptions)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockChangelogService_GetAll_Call) Return(_a0 []readme.Changelog, _a1 *readme.APIResponse, _a2 error) *MockChangelogService_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChangelogService_GetAll_Call) RunAndReturn(run func(...readme.RequestOptions) ([]readme.Changelog, *readme.APIResponse, error)) *MockChangelogService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: slug, params
func (_m *MockChangelogService) Update(slug string, params readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error) {
	ret := _m.Called(slug, params)

	var r0 readme.Changelog
	var r1 *readme.APIResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(string, readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error)); ok {
		return rf(slug, params)
	}
	if rf, ok := ret.Get(0).(func(string, readme.ChangelogParams) readme.Changelog); ok {
		r0 = rf(slug, params)
	} else {
		r0 = ret.Get(0).(readme.Changelog)
	}

	if rf, ok := ret.Get(1).(func(string, readme.ChangelogParams) *readme.APIResponse); ok {
		r1 = rf(slug, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*readme.APIResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(string, readme.ChangelogParams) error); ok {
		r2 = rf(slug, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChangelogService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChangelogService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - slug string
//   - params readme.ChangelogParams
func (_e *MockChangelogService_Expecter) Update(slug interface{}, params interface{}) *MockChangelogService_Update_Call {
	return &MockChangelogService_Update_Call{Call: _e.mock.On("Update", slug, params)}
}

func (_c *MockChangelogService_Update_Call) Run(run func(slug string, params readme.ChangelogParams)) *MockChangelogService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(readme.ChangelogParams))
	})
	return _c
}

func (_c *MockChangelogService_Update_Call) Return(_a0 readme.Changelog, _a1 *readme.APIResponse, _a2 error) *MockChangelogService_Update_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChangelogService_Update_Call) RunAndReturn(run func(string, readme.ChangelogParams) (readme.Changelog, *readme.APIResponse, error)) *MockChangelogService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChangelogService creates a new instance of MockChangelogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangelogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangelogService {
	mock := &MockChangelogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
