# Configuration for golangci-lint
# See https://golangci-lint.run/ for more information.
run:
  concurrency: 4
  timeout: 5m
  # Include test files or not
  tests: false

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupword
    - errcheck
    - errname
    - errorlint
    - funlen
    - goconst
    - gofumpt
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nonamedreturns
    - staticcheck
    - typecheck
    - unused
    - varnamelen
    - wrapcheck

linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
    # Tab width in spaces.
    # Default: 1
    tab-width: 1
